# Generated by Django 2.2 on 2021-05-17 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finalAPP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='created_by',
        ),
    ]
